#ifndef RISCV_MICROK_CONSTANTS_H
#define RISCV_MICROK_CONSTANTS_H

#include "arch.h"

#define FRAME_SIZE 4096
#define PAGE_SIZE FRAME_SIZE
#define LVL1_SIZE 0x400000
#ifdef RV64
#define PAGE_TABLE_NR_SLOTS 512
#else
#define PAGE_TABLE_NR_SLOTS 1024
#endif

#define kIB * (1U << 10U)
#define MiB * (1U << 20U)

#define STACK_SIZE 16384
#define MAX_NR_FRAMES_SUPPORTED 1048576
// TODO: avoid hardcode
#define TIMER_FREQUENCY_BASE 10000000
#define TIMER_CYCLES_PER_SEC TIMER_FREQUENCY_BASE
#define TIMER_CYCLES_PER_MSEC (TIMER_FREQUENCY_BASE / 1000)
// in msecs
#define TASK_TIME_SLICE 100
// 100 msecs
#define TICK_HZ 100
#define TIMER_TICK_INTERVAL (TIMER_CYCLES_PER_MSEC * TICK_HZ)

#ifdef RV64
#define ROOT_PAGE_TABLE_SPARE_INDEX 509
#define ROOT_PAGE_TABLE_SPARE2_INDEX 508
#else
#define ROOT_PAGE_TABLE_SPARE_INDEX 1021
#endif
#define ROOT_PAGE_TABLE_RECURSIVE_INDEX_1 1022
#define ROOT_PAGE_TABLE_RECURSIVE_INDEX_2 1023

#endif //RISCV_MICROK_CONSTANTS_H
