# toolchain params
CC=$(HOST)-gcc
AS=$(HOST)-as

# build modes = normal/debug
BUILD_MODE?=debug

# Compile flags
# TODO: make this configurable
ASFLAGS?=-mabi=ilp32
CFLAGS:=-O0 -std=gnu99 \
	-ffreestanding -fbuiltin -Wall -Wextra
ifeq ($(BUILD_MODE),debug)
CFLAGS:=$(CFLAGS) -gdwarf-4
endif
LIBFLAGS:=-nostdlib

# output directory 
ifeq ($(BUILD_MODE),debug)
BUILD_DIR:=$(shell pwd)/build/debug
else
BUILD_DIR:=$(shell pwd)/build/normal
endif
